#!$(command -v bash)
token=$2
hostname=$3
c1='\033[1;34m'
c2='\033[1;32m'
printf  "$c1

 +-+-+-+-+-+-+ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ 
 |T|e|r|m|u|x| |d|y|n|v|6|-|u|p|d|a|t|e|-|c|l|i|e|n|t| 
 +-+-+-+-+-+-+ +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ v.1
 
"
if [ -z "$hostname" -o -z "$token" ]; then
  echo "Usage: $0 -t authentication-token  your-name.dynv6.your-domain"
  exit 1
fi
#address=$(ip -6 a | awk '/2409/' | sed '2!d' | cut -d/ -f1 | sed 's/inet6//'  | sed 's/ //g')
#address=$(ip -6 a | awk '/inet6/ {print $2}' | sed -n '/^[^ f]/p' | sed 's/\/.*//')
#address=$(ip -6 a | grep -A 10 'rmnet_data2' | awk '/global/' | cut -d/ -f1 | awk '{print $2}')
address=$(ip -6 a | awk '/inet6 2/' | sed -E 's/(^ +[a-z0-9]+) (2[[:alnum:]:/]+).*/\2/' | sed '2d')
#You can use any of above patterns to get addr. since interfaces of everyone's device is
#differnt, we cannot write in a static approach. 


printf "$c2"
if ! command -v curl &> /dev/null
then
    echo "CURL not found, install it!"
    exit
fi
if [ -z "$address" ]; then
  echo "IPv6 address not found"
  exit 1
fi

echo 
$use "http://dynv6.com/api/update?hostname=$hostname&ipv6=$address&token=$token"
echo 

#WRITTEN BY bensh4
#THANKS TO dynv6
